# Generated by Django 5.1.2 on 2024-11-02 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='User_log',
        ),
    ]
