# Generated by Django 5.1.2 on 2024-11-02 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_rename_user_log_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='User_log',
        ),
        migrations.RenameField(
            model_name='user_log',
            old_name='senha',
            new_name='password',
        ),
    ]
