# Generated by Django 5.1.2 on 2024-11-02 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_rename_user_user_log_rename_senha_user_log_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_log',
            old_name='nome',
            new_name='name',
        ),
    ]
